### PR TITLE
Rhel support

### PR DESCRIPTION
**Pull request by dj-wasabi**
Hi,

I added tasks which allow to install this role also on RHEL systems.
Also updated version to latest (stable) release.

Kind regards,
Werner

### CODE REVIEW

**Comment by actionjack** [comment]
Hi @dj-wasabi,

Thanks for the Pull Request!

**Comment by actionjack** [comment]
I just fired it up in vagrant and I can see a couple of issues:

`1.` The latest stable version moves the location of the telegraf conf file from `/etc/opt/influxdb/telegraf.conf` to `/etc/opt/telegraf/telegraf.conf`:

``` diff
diff --git a/tasks/main.yml b/tasks/main.yml
index 587d0d6..b675daf 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -14,6 +14,10 @@
   get_url: url=http://get.influxdb.org/telegraf/telegraf-{{ telegraf_version }}-1.x86_64.rpm dest=/tmp/telegraf_{{ telegraf_version }}-1.x86_64.rpm mode=0440
   when: ansible_os_family == "RedHat"

+- name: install libselinux-python package | RedHat
+  yum: name=libselinux-python state=present
+  when: ansible_os_family == "RedHat"
+
 - name: install telegraf package | RedHat
   yum: name=/tmp/telegraf_{{ telegraf_version }}-1.x86_64.rpm state=installed
   when: ansible_os_family == "RedHat"
@@ -22,6 +26,6 @@
   service: name=telegraf enabled=yes state=started

 - name: Generate telegraf config from template
-  template: src=telegraf.conf.j2 dest=/etc/opt/influxdb/telegraf.conf
+  template: src=telegraf.conf.j2 dest=/etc/opt/telegraf/telegraf.conf
   notify:
     - restart telegraf
```

`2.` There is a missing dependency under Redhat/Centos : 

```
failed: [default] => {"failed": true}
msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
```

**Comment by actionjack** [comment]
@dj-wasabi I can't fix these for you because I don't have commit access to your repo can you fix them on your branch?

**Comment by dj-wasabi** [comment]
Hi,

Sorry for late answer (Was sick last few days), but I've updated the task/main.yml script.

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
Sorry, my bad. Added dependency. Tested with Ubuntu, Redhat and Debian.

**Comment by actionjack** [comment]
Merging thanks @dj-wasabi !

**Pull request merged**
